#ifndef dos_error_h
#define dos_error_h

#define DOSERR_NOT_ENOUGH_MEMORY 100
#define DOSERR_INVALID_NAME		 200
#define DOSERR_BAD_ARGUMENTS     300
#define DOSERR_LINE_TOO_LONG     400
#define DOSERR_NO_PROCESS        500
#define DOSERR_VOLUME_NOT_FOUND  600
#define DOSERR_OBJECT_EXISTS     700
#define DOSERR_OBJECT_WRONG_TYPE 800
#define DOSERR_CANT_LOAD_HANDLER 900

#endif
